export interface CountryCurrencyInfo {
  country: string;
  code: string;
  currencyCode: string;
  currencySymbol: string;
  currencyName: string;
  dialCode: string;
}

export const COUNTRIES_AND_CURRENCIES: CountryCurrencyInfo[] = [
  { country: "Afghanistan", code: "AF", currencyCode: "AFN", currencySymbol: "؜؋", currencyName: "Afghan Afghani", dialCode: "+93" },
  { country: "Albania", code: "AL", currencyCode: "ALL", currencySymbol: "L", currencyName: "Albanian Lek", dialCode: "+355" },
  { country: "Algeria", code: "DZ", currencyCode: "DZD", currencySymbol: "DA", currencyName: "Algerian Dinar", dialCode: "+213" },
  { country: "Andorra", code: "AD", currencyCode: "EUR", currencySymbol: "€", currencyName: "Euro", dialCode: "+376" },
  { country: "Angola", code: "AO", currencyCode: "AOA", currencySymbol: "Kz", currencyName: "Angolan Kwanza", dialCode: "+244" },
  { country: "Argentina", code: "AR", currencyCode: "ARS", currencySymbol: "$", currencyName: "Argentine Peso", dialCode: "+54" },
  { country: "Armenia", code: "AM", currencyCode: "AMD", currencySymbol: "֏", currencyName: "Armenian Dram", dialCode: "+374" },
  { country: "Australia", code: "AU", currencyCode: "AUD", currencySymbol: "$", currencyName: "Australian Dollar", dialCode: "+61" },
  { country: "Austria", code: "AT", currencyCode: "EUR", currencySymbol: "€", currencyName: "Euro", dialCode: "+43" },
  { country: "Azerbaijan", code: "AZ", currencyCode: "AZN", currencySymbol: "₼", currencyName: "Azerbaijani Manat", dialCode: "+994" },
  { country: "Bahamas", code: "BS", currencyCode: "BSD", currencySymbol: "B$", currencyName: "Bahamian Dollar", dialCode: "+1-242" },
  { country: "Bahrain", code: "BH", currencyCode: "BHD", currencySymbol: "BD", currencyName: "Bahraini Dinar", dialCode: "+973" },
  { country: "Bangladesh", code: "BD", currencyCode: "BDT", currencySymbol: "৳", currencyName: "Bangladeshi Taka", dialCode: "+880" },
  { country: "Barbados", code: "BB", currencyCode: "BBD", currencySymbol: "Bds$", currencyName: "Barbadian Dollar", dialCode: "+1-246" },
  { country: "Belarus", code: "BY", currencyCode: "BYN", currencySymbol: "Br", currencyName: "Belarusian Ruble", dialCode: "+375" },
  { country: "Belgium", code: "BE", currencyCode: "EUR", currencySymbol: "€", currencyName: "Euro", dialCode: "+32" },
  { country: "Belize", code: "BZ", currencyCode: "BZD", currencySymbol: "BZ$", currencyName: "Belize Dollar", dialCode: "+501" },
  { country: "Benin", code: "BJ", currencyCode: "XOF", currencySymbol: "CFA", currencyName: "West African CFA franc", dialCode: "+229" },
  { country: "Bermuda", code: "BM", currencyCode: "BMD", currencySymbol: "$", currencyName: "Bermudian Dollar", dialCode: "+1-441" },
  { country: "Bhutan", code: "BT", currencyCode: "BTN", currencySymbol: "Nu.", currencyName: "Bhutanese Ngultrum", dialCode: "+975" },
  { country: "Bolivia", code: "BO", currencyCode: "BOB", currencySymbol: "Bs", currencyName: "Bolivian Boliviano", dialCode: "+591" },
  { country: "Bosnia and Herzegovina", code: "BA", currencyCode: "BAM", currencySymbol: "KM", currencyName: "Bosnia and Herzegovina Convertible Mark", dialCode: "+387" },
  { country: "Botswana", code: "BW", currencyCode: "BWP", currencySymbol: "P", currencyName: "Botswana Pula", dialCode: "+267" },
  { country: "Brazil", code: "BR", currencyCode: "BRL", currencySymbol: "R$", currencyName: "Brazilian Real", dialCode: "+55" },
  { country: "Brunei", code: "BN", currencyCode: "BND", currencySymbol: "$", currencyName: "Brunei Dollar", dialCode: "+673" },
  { country: "Bulgaria", code: "BG", currencyCode: "BGN", currencySymbol: "лв", currencyName: "Bulgarian Lev", dialCode: "+359" },
  { country: "Burkina Faso", code: "BF", currencyCode: "XOF", currencySymbol: "CFA", currencyName: "West African CFA franc", dialCode: "+226" },
  { country: "Burundi", code: "BI", currencyCode: "BIF", currencySymbol: "FBu", currencyName: "Burundian Franc", dialCode: "+257" },
  { country: "Cambodia", code: "KH", currencyCode: "KHR", currencySymbol: "៛", currencyName: "Cambodian Riel", dialCode: "+855" },
  { country: "Cameroon", code: "CM", currencyCode: "XAF", currencySymbol: "CFA", currencyName: "Central African CFA franc", dialCode: "+237" },
  { country: "Canada", code: "CA", currencyCode: "CAD", currencySymbol: "$", currencyName: "Canadian Dollar", dialCode: "+1" },
  { country: "Cape Verde", code: "CV", currencyCode: "CVE", currencySymbol: "Esc", currencyName: "Cape Verdean Escudo", dialCode: "+238" },
  { country: "Central African Republic", code: "CF", currencyCode: "XAF", currencySymbol: "CFA", currencyName: "Central African CFA franc", dialCode: "+236" },
  { country: "Chad", code: "TD", currencyCode: "XAF", currencySymbol: "CFA", currencyName: "Central African CFA franc", dialCode: "+235" },
  { country: "Chile", code: "CL", currencyCode: "CLP", currencySymbol: "$", currencyName: "Chilean Peso", dialCode: "+56" },
  { country: "China", code: "CN", currencyCode: "CNY", currencySymbol: "¥", currencyName: "Chinese Yuan", dialCode: "+86" },
  { country: "Colombia", code: "CO", currencyCode: "COP", currencySymbol: "$", currencyName: "Colombian Peso", dialCode: "+57" },
  { country: "Comoros", code: "KM", currencyCode: "KMF", currencySymbol: "CF", currencyName: "Comorian Franc", dialCode: "+269" },
  { country: "Costa Rica", code: "CR", currencyCode: "CRC", currencySymbol: "₡", currencyName: "Costa Rican Colón", dialCode: "+506" },
  { country: "Croatia", code: "HR", currencyCode: "EUR", currencySymbol: "€", currencyName: "Euro", dialCode: "+385" },
  { country: "Cuba", code: "CU", currencyCode: "CUP", currencySymbol: "₱", currencyName: "Cuban Peso", dialCode: "+53" },
  { country: "Cyprus", code: "CY", currencyCode: "EUR", currencySymbol: "€", currencyName: "Euro", dialCode: "+357" },
  { country: "Czech Republic", code: "CZ", currencyCode: "CZK", currencySymbol: "Kč", currencyName: "Czech Koruna", dialCode: "+420" },
  { country: "Democratic Republic of the Congo", code: "CD", currencyCode: "CDF", currencySymbol: "FC", currencyName: "Congolese Franc", dialCode: "+243" },
  { country: "Denmark", code: "DK", currencyCode: "DKK", currencySymbol: "kr", currencyName: "Danish Krone", dialCode: "+45" },
  { country: "Djibouti", code: "DJ", currencyCode: "DJF", currencySymbol: "Fdj", currencyName: "Djiboutian Franc", dialCode: "+253" },
  { country: "Dominican Republic", code: "DO", currencyCode: "DOP", currencySymbol: "RD$", currencyName: "Dominican Peso", dialCode: "+1-809" },
  { country: "East Timor", code: "TL", currencyCode: "USD", currencySymbol: "$", currencyName: "US Dollar", dialCode: "+670" },
  { country: "Ecuador", code: "EC", currencyCode: "USD", currencySymbol: "$", currencyName: "US Dollar", dialCode: "+593" },
  { country: "Egypt", code: "EG", currencyCode: "EGP", currencySymbol: "E£", currencyName: "Egyptian Pound", dialCode: "+20" },
  { country: "El Salvador", code: "SV", currencyCode: "USD", currencySymbol: "$", currencyName: "US Dollar", dialCode: "+503" },
  { country: "Equatorial Guinea", code: "GQ", currencyCode: "XAF", currencySymbol: "CFA", currencyName: "Central African CFA franc", dialCode: "+240" },
  { country: "Eritrea", code: "ER", currencyCode: "ERN", currencySymbol: "Nfk", currencyName: "Eritrean Nakfa", dialCode: "+291" },
  { country: "Estonia", code: "EE", currencyCode: "EUR", currencySymbol: "€", currencyName: "Euro", dialCode: "+372" },
  { country: "Eswatini (Swaziland)", code: "SZ", currencyCode: "SZL", currencySymbol: "L", currencyName: "Swazi Lilangeni", dialCode: "+268" },
  { country: "Ethiopia", code: "ET", currencyCode: "ETB", currencySymbol: "Br", currencyName: "Ethiopian Birr", dialCode: "+251" },
  { country: "Fiji", code: "FJ", currencyCode: "FJD", currencySymbol: "FJ$", currencyName: "Fijian Dollar", dialCode: "+679" },
  { country: "Finland", code: "FI", currencyCode: "EUR", currencySymbol: "€", currencyName: "Euro", dialCode: "+358" },
  { country: "France", code: "FR", currencyCode: "EUR", currencySymbol: "€", currencyName: "Euro", dialCode: "+33" },
  { country: "Gabon", code: "GA", currencyCode: "XAF", currencySymbol: "CFA", currencyName: "Central African CFA franc", dialCode: "+241" },
  { country: "Gambia", code: "GM", currencyCode: "GMD", currencySymbol: "D", currencyName: "Gambian Dalasi", dialCode: "+220" },
  { country: "Georgia", code: "GE", currencyCode: "GEL", currencySymbol: "₾", currencyName: "Georgian Lari", dialCode: "+995" },
  { country: "Germany", code: "DE", currencyCode: "EUR", currencySymbol: "€", currencyName: "Euro", dialCode: "+49" },
  { country: "Ghana", code: "GH", currencyCode: "GHS", currencySymbol: "GH₵", currencyName: "Ghanaian Cedi", dialCode: "+233" },
  { country: "Greece", code: "GR", currencyCode: "EUR", currencySymbol: "€", currencyName: "Euro", dialCode: "+30" },
  { country: "Guatemala", code: "GT", currencyCode: "GTQ", currencySymbol: "Q", currencyName: "Guatamelan Quetzal", dialCode: "+502" },
  { country: "Guinea", code: "GN", currencyCode: "GNF", currencySymbol: "FG", currencyName: "Guinean Franc", dialCode: "+224" },
  { country: "Guinea-Bissau", code: "GW", currencyCode: "XOF", currencySymbol: "CFA", currencyName: "West African CFA franc", dialCode: "+245" },
  { country: "Guyana", code: "GY", currencyCode: "GYD", currencySymbol: "G$", currencyName: "Guyanese Dollar", dialCode: "+592" },
  { country: "Haiti", code: "HT", currencyCode: "HTG", currencySymbol: "G", currencyName: "Haitian Gourde", dialCode: "+509" },
  { country: "Honduras", code: "HN", currencyCode: "HNL", currencySymbol: "L", currencyName: "Honduran Lempira", dialCode: "+504" },
  { country: "Hong Kong", code: "HK", currencyCode: "HKD", currencySymbol: "$", currencyName: "Hong Kong Dollar", dialCode: "+852" },
  { country: "Hungary", code: "HU", currencyCode: "HUF", currencySymbol: "Ft", currencyName: "Hungarian Forint", dialCode: "+36" },
  { country: "Iceland", code: "IS", currencyCode: "ISK", currencySymbol: "kr", currencyName: "Icelandic Króna", dialCode: "+354" },
  { country: "India", code: "IN", currencyCode: "INR", currencySymbol: "₹", currencyName: "Indian Rupee", dialCode: "+91" },
  { country: "Indonesia", code: "ID", currencyCode: "IDR", currencySymbol: "Rp", currencyName: "Indonesian Rupiah", dialCode: "+62" },
  { country: "Iran", code: "IR", currencyCode: "IRR", currencySymbol: "﷼", currencyName: "Iranian Rial", dialCode: "+98" },
  { country: "Iraq", code: "IQ", currencyCode: "IQD", currencySymbol: "ID", currencyName: "Iraqi Dinar", dialCode: "+964" },
  { country: "Ireland", code: "IE", currencyCode: "EUR", currencySymbol: "€", currencyName: "Euro", dialCode: "+353" },
  { country: "Israel", code: "IL", currencyCode: "ILS", currencySymbol: "₪", currencyName: "Israeli New Shekel", dialCode: "+972" },
  { country: "Italy", code: "IT", currencyCode: "EUR", currencySymbol: "€", currencyName: "Euro", dialCode: "+39" },
  { country: "Ivory Coast", code: "CI", currencyCode: "XOF", currencySymbol: "CFA", currencyName: "West African CFA franc", dialCode: "+225" },
  { country: "Jamaica", code: "JM", currencyCode: "JMD", currencySymbol: "J$", currencyName: "Jamaican Dollar", dialCode: "+1-876" },
  { country: "Japan", code: "JP", currencyCode: "JPY", currencySymbol: "¥", currencyName: "Japanese Yen", dialCode: "+81" },
  { country: "Jordan", code: "JO", currencyCode: "JOD", currencySymbol: "JD", currencyName: "Jordanian Dinar", dialCode: "+962" },
  { country: "Kazakhstan", code: "KZ", currencyCode: "KZT", currencySymbol: "₸", currencyName: "Kazakhstani Tenge", dialCode: "+7" },
  { country: "Kenya", code: "KE", currencyCode: "KES", currencySymbol: "KSh", currencyName: "Kenyan Shilling", dialCode: "+254" },
  { country: "Kiribati", code: "KI", currencyCode: "AUD", currencySymbol: "$", currencyName: "Australian Dollar", dialCode: "+686" },
  { country: "Kuwait", code: "KW", currencyCode: "KWD", currencySymbol: "KD", currencyName: "Kuwaiti Dinar", dialCode: "+965" },
  { country: "Kyrgyzstan", code: "KG", currencyCode: "KGS", currencySymbol: "сом", currencyName: "Kyrgyzstani Som", dialCode: "+996" },
  { country: "Laos", code: "LA", currencyCode: "LAK", currencySymbol: "₭", currencyName: "Lao Kip", dialCode: "+856" },
  { country: "Latvia", code: "LV", currencyCode: "EUR", currencySymbol: "€", currencyName: "Euro", dialCode: "+371" },
  { country: "Lebanon", code: "LB", currencyCode: "LBP", currencySymbol: "L£", currencyName: "Lebanese Pound", dialCode: "+961" },
  { country: "Lesotho", code: "LS", currencyCode: "LSL", currencySymbol: "L", currencyName: "Lesotho Loti", dialCode: "+266" },
  { country: "Liberia", code: "LR", currencyCode: "LRD", currencySymbol: "L$", currencyName: "Liberian Dollar", dialCode: "+231" },
  { country: "Libya", code: "LY", currencyCode: "LYD", currencySymbol: "LD", currencyName: "Libyan Dinar", dialCode: "+218" },
  { country: "Liechtenstein", code: "LI", currencyCode: "CHF", currencySymbol: "CHF", currencyName: "Swiss Franc", dialCode: "+423" },
  { country: "Lithuania", code: "LT", currencyCode: "EUR", currencySymbol: "€", currencyName: "Euro", dialCode: "+370" },
  { country: "Luxembourg", code: "LU", currencyCode: "EUR", currencySymbol: "€", currencyName: "Euro", dialCode: "+352" },
  { country: "Macau", code: "MO", currencyCode: "MOP", currencySymbol: "MOP$", currencyName: "Macanese Pataca", dialCode: "+853" },
  { country: "Madagascar", code: "MG", currencyCode: "MGA", currencySymbol: "Ar", currencyName: "Malagasy Ariary", dialCode: "+261" },
  { country: "Malawi", code: "MW", currencyCode: "MWK", currencySymbol: "MK", currencyName: "Malawian Kwacha", dialCode: "+265" },
  { country: "Malaysia", code: "MY", currencyCode: "MYR", currencySymbol: "RM", currencyName: "Malaysian Ringgit", dialCode: "+60" },
  { country: "Maldives", code: "MV", currencyCode: "MVR", currencySymbol: "Rf", currencyName: "Maldivian Rufiyaa", dialCode: "+960" },
  { country: "Mali", code: "ML", currencyCode: "XOF", currencySymbol: "CFA", currencyName: "West African CFA franc", dialCode: "+223" },
  { country: "Malta", code: "MT", currencyCode: "EUR", currencySymbol: "€", currencyName: "Euro", dialCode: "+356" },
  { country: "Marshall Islands", code: "MH", currencyCode: "USD", currencySymbol: "$", currencyName: "US Dollar", dialCode: "+692" },
  { country: "Mauritania", code: "MR", currencyCode: "MRU", currencySymbol: "UM", currencyName: "Mauritanian Ouguiya", dialCode: "+222" },
  { country: "Mauritius", code: "MU", currencyCode: "MUR", currencySymbol: "₨", currencyName: "Mauritian Rupee", dialCode: "+230" },
  { country: "Mexico", code: "MX", currencyCode: "MXN", currencySymbol: "$", currencyName: "Mexican Peso", dialCode: "+52" },
  { country: "Micronesia", code: "FM", currencyCode: "USD", currencySymbol: "$", currencyName: "US Dollar", dialCode: "+691" },
  { country: "Moldova", code: "MD", currencyCode: "MDL", currencySymbol: "L", currencyName: "Moldovan Leu", dialCode: "+373" },
  { country: "Monaco", code: "MC", currencyCode: "EUR", currencySymbol: "€", currencyName: "Euro", dialCode: "+377" },
  { country: "Mongolia", code: "MN", currencyCode: "MNT", currencySymbol: "₮", currencyName: "Mongolian Tögrög", dialCode: "+976" },
  { country: "Montenegro", code: "ME", currencyCode: "EUR", currencySymbol: "€", currencyName: "Euro", dialCode: "+382" },
  { country: "Morocco", code: "MA", currencyCode: "MAD", currencySymbol: "DH", currencyName: "Moroccan Dirham", dialCode: "+212" },
  { country: "Mozambique", code: "MZ", currencyCode: "MZN", currencySymbol: "MT", currencyName: "Mozambican Metical", dialCode: "+258" },
  { country: "Myanmar", code: "MM", currencyCode: "MMK", currencySymbol: "K", currencyName: "Myanmar Kyat", dialCode: "+95" },
  { country: "Namibia", code: "NA", currencyCode: "NAD", currencySymbol: "$", currencyName: "Namibian Dollar", dialCode: "+264" },
  { country: "Nauru", code: "NR", currencyCode: "AUD", currencySymbol: "$", currencyName: "Australian Dollar", dialCode: "+674" },
  { country: "Nepal", code: "NP", currencyCode: "NPR", currencySymbol: "₨", currencyName: "Nepalese Rupee", dialCode: "+977" },
  { country: "Netherlands", code: "NL", currencyCode: "EUR", currencySymbol: "€", currencyName: "Euro", dialCode: "+31" },
  { country: "New Zealand", code: "NZ", currencyCode: "NZD", currencySymbol: "$", currencyName: "New Zealand Dollar", dialCode: "+64" },
  { country: "Nicaragua", code: "NI", currencyCode: "NIO", currencySymbol: "C$", currencyName: "Nicaraguan Córdoba", dialCode: "+505" },
  { country: "Niger", code: "NE", currencyCode: "XOF", currencySymbol: "CFA", currencyName: "West African CFA franc", dialCode: "+227" },
  { country: "Nigeria", code: "NG", currencyCode: "NGN", currencySymbol: "₦", currencyName: "Nigerian Naira", dialCode: "+234" },
  { country: "North Macedonia", code: "MK", currencyCode: "MKD", currencySymbol: "den", currencyName: "Macedonian Denar", dialCode: "+389" },
  { country: "Norway", code: "NO", currencyCode: "NOK", currencySymbol: "kr", currencyName: "Norwegian Krone", dialCode: "+47" },
  { country: "Oman", code: "OM", currencyCode: "OMR", currencySymbol: "RO", currencyName: "Omani Rial", dialCode: "+968" },
  { country: "Pakistan", code: "PK", currencyCode: "PKR", currencySymbol: "₨", currencyName: "Pakistani Rupee", dialCode: "+92" },
  { country: "Palau", code: "PW", currencyCode: "USD", currencySymbol: "$", currencyName: "US Dollar", dialCode: "+680" },
  { country: "Palestine", code: "PS", currencyCode: "ILS", currencySymbol: "₪", currencyName: "Israeli New Shekel", dialCode: "+970" },
  { country: "Panama", code: "PA", currencyCode: "PAB", currencySymbol: "B/.", currencyName: "Panamanian Balboa", dialCode: "+507" },
  { country: "Papua New Guinea", code: "PG", currencyCode: "PGK", currencySymbol: "K", currencyName: "Papua New Guinean Kina", dialCode: "+675" },
  { country: "Paraguay", code: "PY", currencyCode: "PYG", currencySymbol: "₲", currencyName: "Paraguayan Guaraní", dialCode: "+595" },
  { country: "Peru", code: "PE", currencyCode: "PEN", currencySymbol: "S/.", currencyName: "Peruvian Sol", dialCode: "+51" },
  { country: "Philippines", code: "PH", currencyCode: "PHP", currencySymbol: "₱", currencyName: "Philippine Peso", dialCode: "+63" },
  { country: "Poland", code: "PL", currencyCode: "PLN", currencySymbol: "zł", currencyName: "Polish Złoty", dialCode: "+48" },
  { country: "Portugal", code: "PT", currencyCode: "EUR", currencySymbol: "€", currencyName: "Euro", dialCode: "+351" },
  { country: "Qatar", code: "QA", currencyCode: "QAR", currencySymbol: "QR", currencyName: "Qatari Riyal", dialCode: "+974" },
  { country: "Republic of the Congo", code: "CG", currencyCode: "XAF", currencySymbol: "CFA", currencyName: "Central African CFA franc", dialCode: "+242" },
  { country: "Romania", code: "RO", currencyCode: "RON", currencySymbol: "lei", currencyName: "Romanian Leu", dialCode: "+40" },
  { country: "Russia", code: "RU", currencyCode: "RUB", currencySymbol: "₽", currencyName: "Russian Ruble", dialCode: "+7" },
  { country: "Rwanda", code: "RW", currencyCode: "RWF", currencySymbol: "FRw", currencyName: "Rwandan Franc", dialCode: "+250" },
  { country: "Samoa", code: "WS", currencyCode: "WST", currencySymbol: "WS$", currencyName: "Samoan Tālā", dialCode: "+685" },
  { country: "San Marino", code: "SM", currencyCode: "EUR", currencySymbol: "€", currencyName: "Euro", dialCode: "+378" },
  { country: "Sao Tome and Principe", code: "ST", currencyCode: "STN", currencySymbol: "Db", currencyName: "São Tomé and Príncipe Dobra", dialCode: "+239" },
  { country: "Saudi Arabia", code: "SA", currencyCode: "SAR", currencySymbol: "SR", currencyName: "Saudi Riyal", dialCode: "+966" },
  { country: "Senegal", code: "SN", currencyCode: "XOF", currencySymbol: "CFA", currencyName: "West African CFA franc", dialCode: "+221" },
  { country: "Serbia", code: "RS", currencyCode: "RSD", currencySymbol: "din", currencyName: "Serbian Dinar", dialCode: "+381" },
  { country: "Seychelles", code: "SC", currencyCode: "SCR", currencySymbol: "₨", currencyName: "Seychellois Rupee", dialCode: "+248" },
  { country: "Sierra Leone", code: "SL", currencyCode: "SLE", currencySymbol: "Le", currencyName: "Sierra Leonean Leone", dialCode: "+232" },
  { country: "Singapore", code: "SG", currencyCode: "SGD", currencySymbol: "$", currencyName: "Singapore Dollar", dialCode: "+65" },
  { country: "Slovakia", code: "SK", currencyCode: "EUR", currencySymbol: "€", currencyName: "Euro", dialCode: "+421" },
  { country: "Slovenia", code: "SI", currencyCode: "EUR", currencySymbol: "€", currencyName: "Euro", dialCode: "+386" },
  { country: "Solomon Islands", code: "SB", currencyCode: "SBD", currencySymbol: "SI$", currencyName: "Solomon Islands Dollar", dialCode: "+677" },
  { country: "Somalia", code: "SO", currencyCode: "SOS", currencySymbol: "Sh.So.", currencyName: "Somali Shilling", dialCode: "+252" },
  { country: "South Africa", code: "ZA", currencyCode: "ZAR", currencySymbol: "R", currencyName: "South African Rand", dialCode: "+27" },
  { country: "South Korea", code: "KR", currencyCode: "KRW", currencySymbol: "₩", currencyName: "South Korean Won", dialCode: "+82" },
  { country: "South Sudan", code: "SS", currencyCode: "SSP", currencySymbol: "SSP", currencyName: "South Sudanese Pound", dialCode: "+211" },
  { country: "Spain", code: "ES", currencyCode: "EUR", currencySymbol: "€", currencyName: "Euro", dialCode: "+34" },
  { country: "Sri Lanka", code: "LK", currencyCode: "LKR", currencySymbol: "₨", currencyName: "Sri Lankan Rupee", dialCode: "+94" },
  { country: "Sudan", code: "SD", currencyCode: "SDG", currencySymbol: "SD", currencyName: "Sudanese Pound", dialCode: "+249" },
  { country: "Suriname", code: "SR", currencyCode: "SRD", currencySymbol: "$", currencyName: "Surinamese Dollar", dialCode: "+597" },
  { country: "Sweden", code: "SE", currencyCode: "SEK", currencySymbol: "kr", currencyName: "Swedish Krona", dialCode: "+46" },
  { country: "Switzerland", code: "CH", currencyCode: "CHF", currencySymbol: "CHF", currencyName: "Swiss Franc", dialCode: "+41" },
  { country: "Syria", code: "SY", currencyCode: "SYP", currencySymbol: "LS", currencyName: "Syrian Pound", dialCode: "+963" },
  { country: "Taiwan", code: "TW", currencyCode: "TWD", currencySymbol: "NT$", currencyName: "New Taiwan Dollar", dialCode: "+886" },
  { country: "Tajikistan", code: "TJ", currencyCode: "TJS", currencySymbol: "SM", currencyName: "Tajikistani Somoni", dialCode: "+992" },
  { country: "Tanzania", code: "TZ", currencyCode: "TZS", currencySymbol: "TSh", currencyName: "Tanzanian Shilling", dialCode: "+255" },
  { country: "Thailand", code: "TH", currencyCode: "THB", currencySymbol: "฿", currencyName: "Thai Baht", dialCode: "+66" },
  { country: "Togo", code: "TG", currencyCode: "XOF", currencySymbol: "CFA", currencyName: "West African CFA franc", dialCode: "+228" },
  { country: "Tonga", code: "TO", currencyCode: "TOP", currencySymbol: "T$", currencyName: "Tongan Paʻanga", dialCode: "+676" },
  { country: "Trinidad and Tobago", code: "TT", currencyCode: "TTD", currencySymbol: "TT$", currencyName: "Trinidad and Tobago Dollar", dialCode: "+1-868" },
  { country: "Tunisia", code: "TN", currencyCode: "TND", currencySymbol: "DT", currencyName: "Tunisian Dinar", dialCode: "+216" },
  { country: "Turkey", code: "TR", currencyCode: "TRY", currencySymbol: "₺", currencyName: "Turkish Lira", dialCode: "+90" },
  { country: "Tuvalu", code: "TV", currencyCode: "AUD", currencySymbol: "$", currencyName: "Australian Dollar", dialCode: "+688" },
  { country: "Uganda", code: "UG", currencyCode: "UGX", currencySymbol: "USh", currencyName: "Ugandan Shilling", dialCode: "+256" },
  { country: "Ukraine", code: "UA", currencyCode: "UAH", currencySymbol: "₴", currencyName: "Ukrainian Hryvnia", dialCode: "+380" },
  { country: "United Arab Emirates", code: "AE", currencyCode: "AED", currencySymbol: "د.إ", currencyName: "United Arab Emirates Dirham", dialCode: "+971" },
  { country: "United Kingdom", code: "GB", currencyCode: "GBP", currencySymbol: "£", currencyName: "British Pound", dialCode: "+44" },
  { country: "United States", code: "US", currencyCode: "USD", currencySymbol: "$", currencyName: "US Dollar", dialCode: "+1" },
  { country: "Uruguay", code: "UY", currencyCode: "UYU", currencySymbol: "$U", currencyName: "Uruguayan Peso", dialCode: "+598" },
  { country: "Uzbekistan", code: "UZ", currencyCode: "UZS", currencySymbol: "so'm", currencyName: "Uzbekistani Som", dialCode: "+998" },
  { country: "Vanuatu", code: "VU", currencyCode: "VUV", currencySymbol: "VT", currencyName: "Vanuatu Vatu", dialCode: "+678" },
  { country: "Vatican City", code: "VA", currencyCode: "EUR", currencySymbol: "€", currencyName: "Euro", dialCode: "+379" },
  { country: "Venezuela", code: "VE", currencyCode: "VES", currencySymbol: "Bs.S", currencyName: "Venezuelan Bolívar Soberano", dialCode: "+58" },
  { country: "Vietnam", code: "VN", currencyCode: "VND", currencySymbol: "₫", currencyName: "Vietnamese Đồng", dialCode: "+84" },
  { country: "Yemen", code: "YE", currencyCode: "YER", currencySymbol: "YR", currencyName: "Yemeni Rial", dialCode: "+967" },
  { country: "Zambia", code: "ZM", currencyCode: "ZMW", currencySymbol: "ZK", currencyName: "Zambian Kwacha", dialCode: "+260" },
  { country: "Zimbabwe", code: "ZW", currencyCode: "ZWG", currencySymbol: "ZiG", currencyName: "Zimbabwean Gold", dialCode: "+263" }
];
